In [1]:
import math
import pandas as pd
import numpy as np

In [5]:
df1 = pd.read_csv("Skin_Cancer_Metadata.csv")
df1

         lesion_id      image_id     dx dx_type   age     sex localization
0      HAM_0000118  ISIC_0027419    bkl   histo  80.0    male        scalp
1      HAM_0000118  ISIC_0025030    bkl   histo  80.0    male        scalp
2      HAM_0002730  ISIC_0026769    bkl   histo  80.0    male        scalp
3      HAM_0002730  ISIC_0025661    bkl   histo  80.0    male        scalp
4      HAM_0001466  ISIC_0031633    bkl   histo  75.0    male          ear
...            ...           ...    ...     ...   ...     ...          ...
10010  HAM_0002867  ISIC_0033084  akiec   histo  40.0    male      abdomen
10011  HAM_0002867  ISIC_0033550  akiec   histo  40.0    male      abdomen
10012  HAM_0002867  ISIC_0033536  akiec   histo  40.0    male      abdomen
10013  HAM_0000239  ISIC_0032854  akiec   histo  80.0    male         face
10014  HAM_0003521  ISIC_0032258    mel   histo  70.0  female         back

[10015 rows x 7 columns]

In [6]:
df2 = pd.read_csv("hmnist_8_8_L.csv")
df2

,pixel0000,pixel0001,pixel0002,pixel0003,pixel0004,pixel0005,pixel0006,pixel0007,pixel0008,pixel0009,...,pixel0055,pixel0056,pixel0057,pixel0058,pixel0059,pixel0060,pixel0061,pixel0062,pixel0063,label
0,172,182,191,183,180,181,165,164,173,192,...,159,171,181,201,192,184,183,171,157,2
1,98,149,170,193,183,162,164,100,137,175,...,135,83,159,186,185,192,181,143,58,2
2,165,164,179,172,152,163,169,151,168,174,...,169,152,171,185,189,193,176,168,151,2
3,109,159,167,166,163,159,155,96,141,168,...,101,79,146,170,167,158,154,133,45,2
4,173,202,210,194,208,248,243,205,180,142,...,230,160,199,206,208,209,205,200,186,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10010,193,192,191,198,182,191,213,202,199,204,...,202,206,215,211,207,196,212,205,191,0
10011,93,139,165,183,188,180,150,65,147,164,...,137,145,185,194,186,183,180,161,88,0
10012,165,191,211,227,222,208,210,164,193,203,...,189,184,223,227,218,217,223,207,182,0
10013,138,152,154,161,173,177,179,171,144,157,...,172,143,161,167,166,174,184,175,168,0
10014,152,152,150,148,156,159,158,163,153,155,...,140,143,151,153,156,157,163,117,120,6

In [15]:
merged_df = pd.merge(df1, df2,left_on=None, right_on=None, left_index=False, right_index=False,how='left')

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [8]:
print(df1.head())
print(df2.head())

     lesion_id      image_id   dx dx_type   age   sex localization
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear
   pixel0000  pixel0001  pixel0002  pixel0003  pixel0004  pixel0005  \
0        172        182        191        183        180        181
1         98        149        170        193        183        162
2        165        164        179        172        152        163
3        109        159        167        166        163        159
4        173        202        210        194        208        248

   pixel0006  pixel0007  pixel0008  pixel0009  ...  pixel0055  pixel0056  \
0        165        164        173        192  ...        159        171
1        164        100        137        175  ...        135         83
2        169        151        168        174  ...        169        152
3        155         96        141        168  ...        101         79
4        243        205        180        142  ...        230        160

   pixel0057  pixel0058  pixel0059  pixel0060  pixel0061  pixel0062  \
0        181        201        192        184        183        171
1        159        186        185        192        181        143
2        171        185        189        193        176        168
3        146        170        167        158        154        133
4        199        206        208        209        205        200

   pixel0063  label
0        157      2
1         58      2
2        151      2
3         45      2
4        186      2

[5 rows x 65 columns]

In [9]:
merged_df = pd.merge(df1, df2, left_on='column_in_df1', right_on='column_in_df2', how='left')

KeyError: 'column_in_df2'

In [10]:
merged_df = pd.merge(df1, df2, on='common_column', how='inner')

KeyError: 'common_column'

In [17]:

# Concatenate the two datasets vertically (stacking them on top of each other)
merged_df = pd.concat([df1, df2], ignore_index=True)

merged_df

,lesion_id,image_id,dx,dx_type,age,sex,localization,pixel0000,pixel0001,pixel0002,...,pixel0055,pixel0056,pixel0057,pixel0058,pixel0059,pixel0060,pixel0061,pixel0062,pixel0063,label
0,HAM_0000118,ISIC_0027419,bkl,histo,80.0,male,scalp,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HAM_0000118,ISIC_0025030,bkl,histo,80.0,male,scalp,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HAM_0002730,ISIC_0026769,bkl,histo,80.0,male,scalp,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HAM_0002730,ISIC_0025661,bkl,histo,80.0,male,scalp,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HAM_0001466,ISIC_0031633,bkl,histo,75.0,male,ear,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193.0,192.0,191.0,...,202.0,206.0,215.0,211.0,207.0,196.0,212.0,205.0,191.0,0.0
20026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.0,139.0,165.0,...,137.0,145.0,185.0,194.0,186.0,183.0,180.0,161.0,88.0,0.0
20027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165.0,191.0,211.0,...,189.0,184.0,223.0,227.0,218.0,217.0,223.0,207.0,182.0,0.0
20028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138.0,152.0,154.0,...,172.0,143.0,161.0,167.0,166.0,174.0,184.0,175.0,168.0,0.0
20029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152.0,152.0,150.0,...,140.0,143.0,151.0,153.0,156.0,157.0,163.0,117.0,120.0,6.0

In [18]:
merged_df.head(25)

,lesion_id,image_id,dx,dx_type,age,sex,localization,pixel0000,pixel0001,pixel0002,...,pixel0055,pixel0056,pixel0057,pixel0058,pixel0059,pixel0060,pixel0061,pixel0062,pixel0063,label
0,HAM_0000118,ISIC_0027419,bkl,histo,80.0,male,scalp,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HAM_0000118,ISIC_0025030,bkl,histo,80.0,male,scalp,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HAM_0002730,ISIC_0026769,bkl,histo,80.0,male,scalp,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HAM_0002730,ISIC_0025661,bkl,histo,80.0,male,scalp,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HAM_0001466,ISIC_0031633,bkl,histo,75.0,male,ear,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,HAM_0001466,ISIC_0027850,bkl,histo,75.0,male,ear,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,HAM_0002761,ISIC_0029176,bkl,histo,60.0,male,face,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,HAM_0002761,ISIC_0029068,bkl,histo,60.0,male,face,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,HAM_0005132,ISIC_0025837,bkl,histo,70.0,female,back,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,HAM_0005132,ISIC_0025209,bkl,histo,70.0,female,back,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,HAM_0001396,ISIC_0025276,bkl,histo,55.0,female,trunk,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,HAM_0004234,ISIC_0029396,bkl,histo,85.0,female,chest,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,HAM_0004234,ISIC_0025984,bkl,histo,85.0,female,chest,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,HAM_0001949,ISIC_0025767,bkl,histo,70.0,male,trunk,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,HAM_0001949,ISIC_0032417,bkl,histo,70.0,male,trunk,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,HAM_0007207,ISIC_0031326,bkl,histo,65.0,male,back,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,HAM_0001601,ISIC_0025915,bkl,histo,75.0,male,upper extremity,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,HAM_0001601,ISIC_0031029,bkl,histo,75.0,male,upper extremity,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,HAM_0007571,ISIC_0029836,bkl,histo,70.0,male,chest,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,HAM_0007571,ISIC_0032129,bkl,histo,70.0,male,chest,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,HAM_0006071,ISIC_0032343,bkl,histo,70.0,female,face,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,HAM_0003301,ISIC_0025033,bkl,histo,60.0,male,back,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,HAM_0003301,ISIC_0027310,bkl,histo,60.0,male,back,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,HAM_0004884,ISIC_0032128,bkl,histo,75.0,male,upper extremity,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,HAM_0004884,ISIC_0025937,bkl,histo,75.0,male,upper extremity,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
merged_df.tail(25)

,lesion_id,image_id,dx,dx_type,age,sex,localization,pixel0000,pixel0001,pixel0002,...,pixel0055,pixel0056,pixel0057,pixel0058,pixel0059,pixel0060,pixel0061,pixel0062,pixel0063,label
20005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,216.0,222.0,221.0,...,209.0,203.0,219.0,221.0,219.0,217.0,217.0,220.0,210.0,0.0
20006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158.0,171.0,176.0,...,138.0,182.0,179.0,170.0,175.0,169.0,162.0,149.0,121.0,0.0
20007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,117.0,130.0,...,91.0,106.0,129.0,142.0,142.0,152.0,135.0,119.0,90.0,0.0
20008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174.0,171.0,159.0,...,173.0,166.0,171.0,161.0,147.0,138.0,163.0,171.0,177.0,0.0
20009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150.0,158.0,160.0,...,148.0,144.0,158.0,158.0,166.0,165.0,160.0,154.0,143.0,0.0
20010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,186.0,179.0,166.0,...,155.0,173.0,173.0,163.0,168.0,162.0,160.0,160.0,147.0,0.0
20011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.0,141.0,168.0,...,152.0,134.0,156.0,163.0,167.0,182.0,177.0,165.0,148.0,0.0
20012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,148.0,167.0,181.0,...,166.0,162.0,171.0,162.0,160.0,172.0,169.0,168.0,151.0,0.0
20013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159.0,181.0,197.0,...,142.0,165.0,168.0,162.0,165.0,169.0,169.0,157.0,144.0,0.0
20014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,198.0,207.0,207.0,...,211.0,179.0,191.0,196.0,195.0,186.0,197.0,204.0,206.0,0.0
20015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124.0,145.0,162.0,...,107.0,133.0,150.0,148.0,152.0,158.0,146.0,131.0,117.0,0.0
20016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159.0,175.0,201.0,...,162.0,150.0,175.0,143.0,185.0,200.0,185.0,176.0,154.0,0.0
20017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145.0,167.0,170.0,...,138.0,124.0,164.0,168.0,170.0,182.0,180.0,157.0,125.0,0.0
20018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.0,152.0,158.0,...,105.0,129.0,139.0,146.0,144.0,138.0,131.0,123.0,100.0,0.0
20019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168.0,177.0,169.0,...,182.0,149.0,162.0,171.0,175.0,177.0,173.0,181.0,173.0,0.0
20020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,133.0,155.0,159.0,...,167.0,120.0,145.0,162.0,168.0,172.0,168.0,166.0,154.0,0.0
20021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174.0,197.0,203.0,...,129.0,176.0,191.0,195.0,197.0,192.0,183.0,138.0,100.0,0.0
20022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,26.0,107.0,...,83.0,66.0,143.0,160.0,159.0,138.0,144.0,119.0,31.0,0.0
20023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165.0,181.0,174.0,...,173.0,171.0,157.0,181.0,150.0,162.0,169.0,169.0,168.0,0.0
20024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164.0,161.0,163.0,...,158.0,165.0,165.0,148.0,150.0,150.0,153.0,169.0,160.0,0.0
20025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193.0,192.0,191.0,...,202.0,206.0,215.0,211.0,207.0,196.0,212.0,205.0,191.0,0.0
20026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.0,139.0,165.0,...,137.0,145.0,185.0,194.0,186.0,183.0,180.0,161.0,88.0,0.0
20027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165.0,191.0,211.0,...,189.0,184.0,223.0,227.0,218.0,217.0,223.0,207.0,182.0,0.0
20028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138.0,152.0,154.0,...,172.0,143.0,161.0,167.0,166.0,174.0,184.0,175.0,168.0,0.0
20029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152.0,152.0,150.0,...,140.0,143.0,151.0,153.0,156.0,157.0,163.0,117.0,120.0,6.0

In [20]:
merged_df.mean()

C:\Users\Trisha\AppData\Local\Temp\ipykernel_17556\1393354743.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  merged_df.mean()

age           51.863828
pixel0000    156.511533
pixel0001    167.292461
pixel0002    171.177933
pixel0003    171.134199
                ...
pixel0060    167.451423
pixel0061    167.852322
pixel0062    164.511233
pixel0063    152.323615
label          3.720919
Length: 66, dtype: float64

In [22]:
merged_df.fillna(merged_df.mean(), inplace=True)

C:\Users\Trisha\AppData\Local\Temp\ipykernel_17556\2167644475.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  merged_df.fillna(merged_df.mean(), inplace=True)